version: "3.9"

services:
  app:
    working_dir: /app
    image: golang:1.22.3
    command: sh -c "PORT=8080 DB_USER=admin DB_PWD=admin DB_HOST=db DB_NAME=local DB_SSL_MODE=disable ./bin/_dev.sh"
    volumes:
      - ./:/app
      - go-pkg-mod:/go/pkg/mod:cached
      - go-bin:/go/bin:cached
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gateway_network
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gateway_network
volumes:
  database:
  go-pkg-mod:
  go-bin:
networks:
  gateway_network:
